apiVersion: apps/v1
kind: Deployment
metadata:
  name: ecam-app-deploy
spec:
  selector:
    matchLabels:
      app: ecam-app-deploy
  template:
    metadata:
      name: ecam-app
      labels:
        app: ecam-app-deploy
    spec:
      containers:
      - image: tanminkwan/ecam-app
        imagePullPolicy: Always
        name: ecam-app-con
        env:
        - name: DATABASE_URI
          valueFrom:
            secretKeyRef:
              name: db-connections
              key: database-uri
        - name: REDIS_URI
          valueFrom:
            secretKeyRef:
              name: db-connections
              key: redis-uri
        - name: STREAM_URL
          valueFrom:
            configMapKeyRef:
              name: envs-ecam-app
              key: stream-server-url
        ports:
        - containerPort: 5000
          protocol: TCP
        volumeMounts:
        - mountPath: "/static/uploads"
          name: ecam-app-vol
      volumes:
      - name: ecam-app-vol
        persistentVolumeClaim:
          claimName: ecam-pvc
  replicas: 3