apiVersion: v1
kind: Service
metadata:
  name: ecam-cms-service-nodeport
spec:
  type: NodePort
  selector:
    app: ecam-cms-deploy
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 30180
