apiVersion: v1
kind: Service
metadata:
  name: ecam-app-service-nodeport
spec:
  type: NodePort
  selector:
    app: ecam-app-deploy
  ports:
  - protocol: TCP
    port: 80
    targetPort: 5000
    nodePort: 30080
